[package]
name = "capitalcommander-ui-rs"
version = "0.1.0"
authors = ["Andy Nagels <thereisanewway@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "3"
tera = "1.16"
serde = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
